nbtoptran/urls.py
from django.conf.urls import url, include
from django.contrib import admin




from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^filer/', include('filer.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
   url(r'', include('toptran.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toptran/urls.py
from django.conf.urls import url

from . import views


app_name = 'toptran'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    
    url(r'^news$', views.NewsView.as_view(), name='news'),
    url(r'^news/(?P<pk>[0-9]+)/$', views.newsdetail, name='newsdetail'),

    url(r'^knowledge$', views.KnowledgeView.as_view(), name='knowledge'),
    url(r'^knowledge/(?P<pk>[0-9]+)/$', views.knowledgedetail, name='knowledgedetail'),

    url(r'^contact$', views.contact, name='contact'),
    url(r'^about$', views.about, name='about'),
    url(r'^case$', views.CaseView.as_view(), name='case'),
    url(r'^product$', views.product_list, name='product_list'),
    url(r'^product/(?P<category_slug>[-\w]+)/$',views.product_list,name='product_list_by_category'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
    
]

toptran/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from filer.fields.image import FilerImageField
from ckeditor.fields import RichTextField
# Create your models here.
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Category(models.Model):
	name = models.CharField(max_length=200,db_index=True)
	slug = models.SlugField(max_length=200,db_index=True,unique=True)
	

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'


	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('toptran:product_list_by_category',args=[self.slug])

   


@python_2_unicode_compatible
class Product(models.Model):
	category = models.ForeignKey(Category,related_name='products')

	name = models.CharField(max_length=200,db_index=True)
	slug = models.SlugField(max_length=200,db_index=True)
	image = FilerImageField(null=True,blank=True,related_name='products_image')
	description = RichTextField(blank=True,null=True,verbose_name="description")
	


	class Meta:
		ordering = ('name',)
		index_together = (('id','slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('toptran:product_detail',args=[self.id,self.slug])



@python_2_unicode_compatible
class News(models.Model):
	image = FilerImageField(null=True,blank=True,related_name='news_image')
	title = models.CharField(max_length=200)
	body = RichTextField(blank=True,null=True,verbose_name="body")
	pub_date = models.DateTimeField(default=timezone.now)
	views = models.PositiveIntegerField(default=0)


	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])
   


	class Meta():
		ordering = ['-pub_date']

	def __str__(self):
		return self.title

	# 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数

	def get_absolute_url(self):
		return reverse('toptran:newsdetail', kwargs={'pk': self.pk})


@python_2_unicode_compatible
class Case(models.Model):
	image = FilerImageField(null=True,blank=True,related_name='case_image')

@python_2_unicode_compatible
class Index(models.Model):
	image = FilerImageField(null=True,blank=True,related_name='index_image')

	

@python_2_unicode_compatible
class Knowledge(models.Model):
	image = FilerImageField(null=True,blank=True,related_name='knowledge_image')
	title = models.CharField(max_length=200)
	body = RichTextField(blank=True,null=True,verbose_name="body")
	pub_date = models.DateTimeField(default=timezone.now)
	views = models.PositiveIntegerField(default=0)


	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])
   


	class Meta():
		ordering = ['-pub_date']

	def __str__(self):
		return self.title

	# 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数

	def get_absolute_url(self):
		return reverse('toptran:knowledgedetail', kwargs={'pk': self.pk})

toptran/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import ListView
import markdown
from toptran import models
from django.shortcuts import render,get_object_or_404

from .models import News,Knowledge,Case,Index,Category,Product



def index(request):
	index_list = Index.objects.all()
	return render(request, 'toptran/index.html', context={'index_list': index_list})




#以下被NewsView类代替：
#def news(request):
	#news_list = News.objects.all()
	#return render(request, 'toptran/news.html', context={'news_list': news_list})
class NewsView(ListView):
	model = News
	template_name = 'toptran/news.html'
	context_object_name = 'news_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章

	paginate_by = 10
	def get_context_data(self, **kwargs):


  
        #在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        #例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        #这里传递了一个 {'post_list': post_list} 字典给模板。
        #在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        #所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
     

        # 首先获得父类生成的传递给模板的字典。

		context = super().get_context_data(**kwargs)


        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
		pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
		context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:

            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
			return {}

        # 当前页左边连续的页码号，初始值为空
		left = []

        # 当前页右边连续的页码号，初始值为空
		right = []

        # 标示第 1 页页码后是否需要显示省略号
		left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
		right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
		first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
		last = False

        # 获得用户当前请求的页码号
		page_number = page.number

        # 获得分页后的总页数
		total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
		page_range = paginator.page_range

		if page_number == 1:


            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
			right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
			if right[-1] < total_pages - 1:

				right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
			if left[0] > 2:
				left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
			if left[0] > 1:
				first = True
		else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
			if right[-1] < total_pages - 1:

				right_has_more = True
			if right[-1] < total_pages:
				last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
			if left[0] > 2:

				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

		return data


def newsdetail(request,pk):

	news = get_object_or_404(News,pk=pk)
	news.increase_views()
	news.body = markdown.markdown(news.body,
		                          extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
	return render(request,'toptran/newsdetail.html',context={'news':news})






class KnowledgeView(ListView):
	model = Knowledge
	template_name = 'toptran/knowledge.html'
	context_object_name = 'knowledge_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章

	paginate_by = 10
	def get_context_data(self, **kwargs):

  
        #在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        #例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        #这里传递了一个 {'post_list': post_list} 字典给模板。
        #在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        #所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
     

        # 首先获得父类生成的传递给模板的字典。

		context = super().get_context_data(**kwargs)


        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
		pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
		context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:

            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
			return {}

        # 当前页左边连续的页码号，初始值为空
		left = []

        # 当前页右边连续的页码号，初始值为空
		right = []

        # 标示第 1 页页码后是否需要显示省略号
		left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
		right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
		first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
		last = False

        # 获得用户当前请求的页码号
		page_number = page.number

        # 获得分页后的总页数
		total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
		page_range = paginator.page_range

		if page_number == 1:


            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
			right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
			if right[-1] < total_pages - 1:

				right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
			if left[0] > 2:
				left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
			if left[0] > 1:
				first = True
		else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
			if right[-1] < total_pages - 1:

				right_has_more = True
			if right[-1] < total_pages:
				last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
			if left[0] > 2:

				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

		return data


def knowledgedetail(request,pk):

	knowledge = get_object_or_404(Knowledge,pk=pk)
	knowledge.increase_views()
	knowledge.body = markdown.markdown(knowledge.body,
		                          extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])

templates/toptran/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>冲床自动化设备采购需求请联系宁波拓诚机械有限公司18968331230</title>
  <meta name="keywords" content="冲床自动化设备采购" />
  <meta name="description" content="冲床自动化设备采购需求请联系宁波拓诚机械有限公司18968331230.公司拥有多年研制,服务经验,为您提供专业的冲压加工生产线,三合一料架整平送料机,二合一料架整平机,NC伺服送料机,精密整平机产品,需要就赶快拿起电话订购吧!" />
  <!--产品中心-->
  {% block title %}
 
{% endblock %}
 
</head>
<body>
  
{% block content %}
{% endblock %}

{% include 'toptran/footer.html' %}


  

  
 
  
</body>
</html>

templates/toptran/case.html
{% extends 'toptran/base.html' %}

{% load staticfiles %}







{% block title %}

    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/case.css' %}">  
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">  
<link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
 <!--返回顶部-->
   <link rel="stylesheet" href="{% static 'case/css/lc_lightbox.css' %}" />
  <!-- SKINS -->
  <link rel="stylesheet" href="{% static 'case/skins/minimal.css' %}" />
  <!-- 示例页面基本样式 -->
  <style type="text/css">
     .elem, .elem * {
    box-sizing: border-box;
    margin: 0 !important; 
  }
  .elem {
    display: inline-block;
    font-size: 0;
    width: 33%;
    border: 20px solid transparent;
    border-bottom: none;
    background: #fff;
    padding: 10px;
    height: auto;
    background-clip: padding-box;
  }
  .elem > span {
    display: block;
    cursor: pointer;
    height: 0;
    padding-bottom: 70%;
    background-size: cover; 
    background-position: center center;
  }
  </style>
  <!-- LIGHTBOX FADING SHOW/HIDE EFFECT (as explained in documentation) -->
  <style type="text/css">
  .lcl_fade_oc.lcl_pre_show #lcl_overlay,
  .lcl_fade_oc.lcl_pre_show #lcl_window,
  .lcl_fade_oc.lcl_is_closing #lcl_overlay,
  .lcl_fade_oc.lcl_is_closing #lcl_window {
    opacity: 0 !important;
  }
  .lcl_fade_oc.lcl_is_closing #lcl_overlay {
    -webkit-transition-delay: .15s !important; 
    transition-delay: .15s !important;
  }
  </style>



  <script src="http://cdn.bootcss.com/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
  <script>window.jQuery || document.write('<script src="{% static 'case/js/jquery-1.11.0.min.js' %}"><\/script>')</script>
  <script src="{% static 'case/js/lc_lightbox.lite.js' %}" type="text/javascript"></script>
  <!-- ASSETS -->
  <script src="{% static 'case/lib/AlloyFinger/alloy_finger.min.js' %}" type="text/javascript"></script>
  <script type="text/javascript">
    $(document).ready(function(e) {
      // live handler
      lc_lightbox('.elem', {
        wrap_class: 'lcl_fade_oc',
        gallery : true, 
        thumb_attr: 'data-lcl-thumb', 
        
        skin: 'minimal',
        radius: 0,
        padding : 0,
        border_w: 0,
      }); 

    });
  </script>

{% endblock %}

{% block content %}
<div class="header">

    <nav>
        <ul>
           <li><a href="{% url 'toptran:index' %}"><div><img src="{% static 'img/LOGO.png' %}"></div></a></li>
           <li class="nav"><a href="{% url 'toptran:about' %}">关于我们</a></li>
           <li class="nav"><a href="{% url 'toptran:product_list' %}">产品中心</a></li>
           <li class="cont"><a href="{% url 'toptran:case' %}">成功案例</a></li>
           <li class="nav"><a href="{% url 'toptran:news' %}">新闻中心</a></li>
           <li class="nav"><a href="{% url 'toptran:knowledge' %}">行业知识</a></li>
           <li class="nav"><a href="{% url 'toptran:contact' %}">联系我们</a></li>
        </ul>
  </nav>
  <div class="banner"></div>
</div>


<div class="news">
            <div class="mbx_nav">
                <p>成功案例
                	<span>您当前位置： 
                    	<a href="/">
                        <i class="fa fa-home heading-icon" aria-hidden="true"></i></a> >
                        <span>成功案例</span>
                    </span>
                </p>
            </div>
            <div class="dc new_list">

          
          <div class="content">
            
       {% for case in case_list %}
      <a  class="elem" href="{{ case.image.url }}" title="" data-lcl-txt="" data-lcl-author="" data-lcl-thumb="{{ case.image.url }}">
          <span style="background-image: url({{ case.image.url }})"></span>
          </a>
       {% empty %}
       <div>暂时还没有发布的案例！</div>

       {% endfor %}
         

        <br/><br/>
</div>
 

</div>

</div>

{% if is_paginated %}
<div id="pgServer" class="page">
  {% if first %}
 
    <a href="?page=1">1</a>
  {% endif %}
  {% if left %}
    {% if left_has_more %}
        <span>...</span>
    {% endif %}
    {% for i in left %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
  {% endif %}
  <a  href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
  {% if right %}
    {% for i in right %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% if right_has_more %}
        <span>...</span>
    {% endif %}
  {% endif %}
  {% if last %}
    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
  {% endif %}
</div>
{% endif %}
<br>
<br>
<br>
<br>
</div>
{% endblock %}

templates/toptran/knowledge.html
{% extends 'toptran/base.html' %}

{% load staticfiles %}





{% block title %}

    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/knowledge.css' %}">  
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">  
<link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
 <!--返回顶部-->
{% endblock %}    

{% block content %}

<div class="header">

    <nav>
        <ul>
           <li><a href="{% url 'toptran:index' %}"><div><img src="{% static 'img/LOGO.png' %}"></div></a></li>
           <li class="nav"><a href="{% url 'toptran:about' %}">关于我们</a></li>
           <li class="nav"><a href="{% url 'toptran:product_list' %}">产品中心</a></li>
           <li class="nav"><a href="{% url 'toptran:case' %}">成功案例</a></li>
           <li class="nav"><a href="{% url 'toptran:news' %}">新闻中心</a></li>
           <li class="cont"><a href="{% url 'toptran:knowledge' %}">行业知识</a></li>
           <li class="nav"><a href="{% url 'toptran:contact' %}">联系我们</a></li>
        </ul>
  </nav>
  <div class="banner"></div>
</div>


<div class="news">
            <div class="mbx_nav">
                <p>行业知识
                  <span>您当前位置：
                      <a href="{% url 'toptran:index' %}">
                        <i class="fa fa-home heading-icon" aria-hidden="true"></i></a> >
                        <span>行业知识</span>
                    </span>
                </p>
            </div>


            {% for knowledge in knowledge_list %}
            <div class="dc new_list ">


                      <div class="nl_left">
                          <p><a href="{{ knowledge.get_absolute_url }}"><img src="{% static 'img/news_logo.jpg' %}"></a></p>
                      </div>
                      <br>
                       <br>
                      <div class="nl_right">
                          <p class="new_p1"><a href="{{ knowledge.get_absolute_url }}">{{ knowledge.title }}</a></p>

                            <p style="font-size: 120%;">{{ knowledge.body|truncatechars:80 }}</</p>
                            <p class="new_p2"><a href="{{ knowledge.get_absolute_url }}">查看详情>> </a></p>

                      </div>




            </div>
            {% empty %}
            <div>暂时还没有发布的文章！</div>

            {% endfor %}
</div>

<br>
<br>
<br>
<br>
<br>


{% if is_paginated %}
<div id="pgServer" class="page">
  {% if first %}
 
    <a href="?page=1">1</a>
  {% endif %}
  {% if left %}
    {% if left_has_more %}
        <span>...</span>
    {% endif %}
    {% for i in left %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
  {% endif %}
  <a  href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
  {% if right %}
    {% for i in right %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% if right_has_more %}
        <span>...</span>
    {% endif %}
  {% endif %}
  {% if last %}
    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
  {% endif %}
</div>
{% endif %}
<br>
<br>
<br>
<br>
<!-- 如果当前页还有上一页，显示一个上一页的按钮
<div id="pgServer" class="page">
<a class="prev" class="prev" disabled="disabled" style="margin-right:5px;"> < </a><span class="cur" style="margin-right:5px;">1</span><a href="/news/default.aspx?page=2" style="margin-right:5px;">2</a><a href="/news/default.aspx?page=3" style="margin-right:5px;">3</a><a href="/news/default.aspx?page=4" style="margin-right:5px;">4</a><a href="/news/default.aspx?page=5" style="margin-right:5px;">5</a><a href="/news/default.aspx?page=6" style="margin-right:5px;">6</a><a href="/news/default.aspx?page=7" style="margin-right:5px;">7</a><a href="/news/default.aspx?page=8" style="margin-right:5px;">8</a><a href="/news/default.aspx?page=9" style="margin-right:5px;">9</a><a href="/news/default.aspx?page=10" style="margin-right:5px;">10</a><a class="next" class="next" href="/news/default.aspx?page=2" style="margin-right:5px;"> > </a>
</div>-->

{% endblock %}